### ISSUE TITLE
大佬，想请教你个问题。

### ISSUE THREAD

**Issue by srcrs** [happy888888/baidu-sign#1]
https://tieba.baidu.com/mo/q/newmoindex 这个接口你是怎么抓取到的，为什么我在浏览器上一直都没有看到。

**Comment by happy888888** [comment]
电脑浏览器看不到，把电脑浏览器ua改成安卓的，进入百度首页就是手机版的，再点击贴吧，也是手机版的(不是指app版，app接口是另外一个，这是手机版网页，还是算网页版)，然后展开贴吧列表(展开前只显示20个，展开后是200个)，就能找到这个接口

**Comment by happy888888** [comment]
关键就是改浏览器ua，让百度把电脑浏览器当成手机浏览器返回手机版网页，一般手机版网页都要简洁一些，同样适用于其他网站

**Comment by srcrs** [comment]
好的，谢谢你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 晚上9:36
收件人: "happy888888/baidu-sign"<baidu-sign@noreply.github.com&gt;; 
抄送: "srcrs"<srcrs@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [happy888888/baidu-sign] 大佬，想请教你个问题。 (#1)





 
电脑浏览器看不到，把电脑浏览器ua改成安卓的，进入百度首页就是手机版的，再点击贴吧，也是手机版的(不是指app版，app接口是另外一个，这是手机版网页，还是算网页版)，然后展开贴吧列表(展开前只显示20个，展开后是200个)，就能找到这个接口

**Comment by srcrs** [comment]
我在手机上抓的包显示的是另一个，感觉你这个get方法挺牛的

**Comment by happy888888** [comment]
手机app版的接口也只能获取前200个，还要使用md5加密，不如就用网页版的

**Comment by srcrs** [comment]
是的。
